services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-volume:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: /bin/sh
    command: -c "
      ollama serve &
      sleep 15 &&
      ollama pull deepseek-r1:7b &&
      tail -f /dev/null &&
      ollama list
      "

volumes:
  ollama-volume:
